// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLv6jwvgqms97G8L0GEee3hF64T7PB1Io',
    appId: '1:985617598644:web:2845ed41b7694b8472afe1',
    messagingSenderId: '985617598644',
    projectId: 'tubes-iot-1bb8c',
    authDomain: 'tubes-iot-1bb8c.firebaseapp.com',
    databaseURL: 'https://tubes-iot-1bb8c-default-rtdb.firebaseio.com',
    storageBucket: 'tubes-iot-1bb8c.firebasestorage.app',
    measurementId: 'G-JCJFG6NNSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3PSR4uMBw2-TeFaoFGUVGYWBwZBDMMXc',
    appId: '1:985617598644:android:e0cebebcaacbff6072afe1',
    messagingSenderId: '985617598644',
    projectId: 'tubes-iot-1bb8c',
    databaseURL: 'https://tubes-iot-1bb8c-default-rtdb.firebaseio.com',
    storageBucket: 'tubes-iot-1bb8c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLv6jwvgqms97G8L0GEee3hF64T7PB1Io',
    appId: '1:985617598644:web:7c609552d1b8f55372afe1',
    messagingSenderId: '985617598644',
    projectId: 'tubes-iot-1bb8c',
    authDomain: 'tubes-iot-1bb8c.firebaseapp.com',
    databaseURL: 'https://tubes-iot-1bb8c-default-rtdb.firebaseio.com',
    storageBucket: 'tubes-iot-1bb8c.firebasestorage.app',
    measurementId: 'G-DQ6VSWVWEF',
  );
}
